/*
*********************************************************************************************************
*   											uC/OS-II
*   											实时内核
*
*   					 (c) Copyright 1992-1998, Jean J. Labrosse, Plantation, FL
*   											版权所有
*                                       STC89C58RD+ Specific code
*   										
*
* 文件名 : INCLUDES.H
* 作者   : Jean J. Labrosse
* Modify	   : StrongZhai
* Date  	   : 27-Aug-11
*********************************************************************************************************
*/

#include	<stdarg.h>
#include	<stdio.h>
#include	<string.h>
#include	<ctype.h>
#include	<stdlib.h>
#include	<setjmp.h>

#include	"os_cpu.h"
#include	"os_cfg.h"
#include	"\OSS\ucos_ii.h"
#include    "COMMRTOS.h"

#include <reg52.h>
#include <intrins.h>

